#!/bin/bash
# Generated by run_cmd_creater.py
# Date: 20260322
# Total tests: 4

# Test 1: testlist/tc_basic_read
source /etc/profile && bsub -q to2 -Is  run -l testlist/tc_basic_read 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_basic_read -g  -p 15  -seed_offset 20260322 -sim "+UVM_VERBOSITY=UVM_NONE" -b "bsub -q to2 -Is  timeout 2400m "&
source /etc/profile && bsub -q to2 -Is  run -l testlist/tc_basic_read 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_basic_read -g  -p 15  -seed_offset 20260322 -sim "+UVM_VERBOSITY=UVM_NONE" -t basic_read_test -b "bsub -q to2 -Is  timeout 2400m "&
source /etc/profile && bsub -q to2 -Is  run -l testlist/tc_basic_read 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_basic_read -g  -p 15  -seed_offset 20260322 -sim "+UVM_VERBOSITY=UVM_HIGH" -t basic_read_test_with_extra -b "bsub -q to2 -Is  timeout 2400m "&

# Test 2: testlist/tc_basic_write
source /etc/profile && bsub -q to2 -Is  run -l testlist/tc_basic_write 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_basic_write -g  -p 15  -seed_offset 20260322  -b "bsub -q to2 -Is  timeout 2400m "&
source /etc/profile && bsub -q to2 -Is  run -l testlist/tc_basic_write 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_basic_write -g  -p 15  -seed_offset 20260322  -t basic_write_test -b "bsub -q to2 -Is  timeout 2400m "&

# Test 3: testlist/tc_burst_transfer
bsub -q to2 -Is  run -l testlist/tc_burst_transfer 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_burst_transfer -g  -p 15  -seed_offset 20260322  -b "bsub -q to2 -Is  timeout 2400m "&
bsub -q to2 -Is  run -l testlist/tc_burst_transfer 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_burst_transfer -g  -p 15  -seed_offset 20260322  -t burst_transfer_test -b "bsub -q to2 -Is  timeout 2400m "&

# Test 4: testlist/tc_error_handling
cd /path/to/error_test && source env.csh && export DEBUG=1 && bsub -q to2 -Is  run -l testlist/tc_error_handling 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_error_handling -g  -p 15  -seed_offset 20260322  -b "bsub -q to2 -Is  timeout 2400m "&
cd /path/to/error_test && source env.csh && export DEBUG=1 && bsub -q to2 -Is  run -l testlist/tc_error_handling 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_error_handling -g  -p 15  -seed_offset 20260322  -t axi_pass_test -b "bsub -q to2 -Is  timeout 2400m "&
cd /path/to/error_test && source env.csh && export DEBUG=2 && bsub -q to2 -Is  run -l testlist/tc_error_handling 	 -sim "-cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260322/tc_error_handling -g  -p 15  -seed_offset 20260322 -sim "+UVM_VERBOSITY=UVM_HIGH" -t axi_pass_test_with_debug -b "bsub -q to2 -Is  timeout 2400m "&

