instrlist = [
    # "instr_inference_test",
    # "instr_inference_performance_test",
    # "instr_calibration_test",
    # "instr_program_test",
    # "instr_program_process1_test",
    # "instr_voltageread_test",
    # "instr_currentread_test",
    # "instr_inferread_test",
    # "instr_erase_test",
    # "instr_configimm_test",
    # "instr_configsingle_test",
    # "instr_configsingle_table_test",
    # "instr_configburst_test",
    # "instr_configburst_table_test",
    # "instr_readburst_test",
    # "instr_readburst_table_test",
    # "instr_writetiabuffer_test",
    # "instr_writecompbuffer_test",
    # "instr_writebuffer_test",
    # "instr_bypass_test",
    # "instr_fence_test",
    # "instr_delay_test",
    # "instr_tia_test",
    # "instr_tia_part_test",
    # "instr_comp_test",
    # "instr_erase_program_calibration_test",
    # "instr_erase_program_currentread_test",
    # "instr_erase_program_currentread_1table_test",
    # "instr_erase_program_inferread_test",
    # "instr_erase_program_inferread_1table_test",
    # "instr_erase_program_inference_test",
    # "instr_erase_program_inference_1table_test",
    # "instr_erase_program_voltageread_test",
    # "instr_erase_program_voltageread_1table_test",
    # "instr_infer_bypass_test",
    # "instr_infer_calibration_test",
    # "instr_infer_currentread_test",
    # "instr_infer_erase_test",
    # "instr_infer_erase_1table_test",
    # "instr_infer_inferread_test",
    # "instr_infer_program_test",
    # "instr_infer_program_1table_test",
    # "instr_infer_voltageread_test",
    # "instr_layer_sel_test",
    # "reg_cfg_test",
    # "instr_config_fence_test",
    # "instr_currentread_fence_test",
    # "instr_erase_fence_test",
    # "instr_inferread_fence_test",
    # "instr_program_fence_test",
    # "instr_voltageread_fence_test",
    # "instr_config_delay_test",
    # "instr_erase_delay_test",
    # "instr_program_delay_test",
    # "instr_currentread_delay_test",
    # "instr_inferread_delay_test",
    # "instr_voltageread_delay_test",
    # "instr_calibration_erase_test",
    # "instr_calibration_program_test",
    # "instr_calibration_currentread_test",
    # "instr_calibration_inferread_test",
    # "instr_calibration_voltageread_test",
    # "instr_switch_test",
    # "instr_switch_1table_test",
    # "instr_switch_1table_list1_test",
    # "rcc_reg_test",
    # "reg_map_reg_test",
    # "common_reg_test",
    # "dacfifo5_reg_test",
    # "post_ctrl_reg_test",
    # "pipepre_reg_test",
    # "prim_register_reg_test",
    # "comp_sram_wr_rd_test",
    # "boundary_config_regaddr_test",
    # "tia_sram_wr_rd_test",
    # "logic_reg_perf_test",
    # "flash_reg_pref_test",
    # "regall_reg_test",
    # "tia_backdoor_test",
    # "pvt_reg_reg_test",
    # "comp_backdoor_test",
    # "regall_addr_scan_test",
    # "regall_outaddr_scan_test",
    # "buffer_multi_wr_rd_test",
    # "comp_same_addr_wr_rd_test",
    # "single_infer_pipemode1_test",
    # "single_infer_pipemode2_test",
    # "single_infer_pipemode3_test",
    # "single_infer_pipemode1_rand_test",
    # "single_infer_pipemode2_rand_test",
    # "single_infer_pipemode3_rand_test",
    # "multi_infer_pipemode1_test",
    # "multi_infer_pipemode2_test",
    # "multi_infer_pipemode3_test",
    # "multi_infer_pipemode1_rand_test",
    # "multi_infer_pipemode2_rand_test",
    # "multi_infer_pipemode3_rand_test",
    # "multi_infer_pipemode1_min_test",
    # "multi_infer_pipemode2_min_test",
    # "multi_infer_pipemode3_min_test",
    # "multi_infer_pipemode1_max_test",
    # "multi_infer_pipemode2_max_test",
    # "multi_infer_pipemode3_max_test",
    # "infer_row_remap_test",
    # "infer_col_remap_test",
    # "infer_pre_scale_test",
    # "infer_post_comp_test",
    # "infer_post_scale_test",
    # "infer_post_shift_test",
    # "infer_post_cascade_test",
    # "pre_currentread_test",
    # "pre_currentread_red_test",
    # "pre_inferread_test",
    # "pre_inferread_red_test",
    # "pre_dactest_test",
    # "post_read_test",
    # "post_adctest_test",
    # "post_dactest_test",
    # "post_readburst_test",
    # "boundary_bypass_test",
    # "boundary_config_regaddr_test",
    # "boundary_calibration_test",
    # "boundary_config_test",
    # "boundary_currentread_test",
    # "boundary_delay_test",
    # "boundary_erase_test",
    # "boundary_inference_test",
    # "boundary_inferread_test",
    # "boundary_program_test",
    # "boundary_voltageread_test",
    # "boundary_writebuffer_test",
    # "instr_infer_redundant_row_test",
    # "instr_infer_redundant_bias_test",
    # "instr_infer_redundant_col_test",
    # "instr_redundant_currentread_test",
    # "instr_redundant_erase_test",
    # "instr_redundant_inferread_test",
    # "instr_redundant_program_test",
    # "instr_redundant_voltageread_test",
    # "instr_redundant_inference_test",
    # "blsel_currentread_test",
    # "blsel_inferread_test",
    # "blsel_instr_switch_test",
    # "blsel_program_test",
    # "blsel_voltageread_test",
    # "instr_debugdac_test",
    # "instr_debugdac_apb_test",
    # "inster_addctest_test",
    # "inster_dactest_test",
    # "instr_dactest_customize_length_test",
    # "instr_dactest_customize_length_pad_test",
    # "instr_dactest_customize_length_bypasstia_test",
    # "nop_calibration_test",
    # "nop_config_test",
    # "nop_currentread_test",
    # "nop_delay_test",
    # "nop_erase_test",
    # "nop_fence_test",
    # "nop_inference_test",
    # "nop_inferread_test",
    # "nop_program_test",
    # "nop_voltageread_test",
    # "nop_writecompbuffer_test",
    # "nop_writetiabuffer_test",
    # "reuse_inference_test",
    # "reuse_inference_calibration_test",
    # "reuse_calibration_test",
    # "backpress_infer_opkt_first_test",
    # "backpress_infer_opkt_mid_test",
    # "backpress_infer_opkt_test",
    # "backpress_calib_opkt_test",
    # "backpress_infer_calib_opkt_test",
    # "backpress_infer_ipkt_test",
    # "cellsum_calibration_test",
    # "cellsum_currentread_test",
    # "cellsum_inference_test",
    # "cellsum_inferread_test",
    # "cellsum_voltagread_test",
    # "dscarrayctrl_infer_freeze_test",
    # "reset_in_idle_test",
    # "reset_barrier_id_test",
    # "instr_currentread_3stage_test",
    # "instr_inference_3stage_test",
    # "instr_inferread_3stage_test",
    # "instr_program_3stage_cg_test",
    # "instr_program_3stage_s1_test",
    # "instr_voltageread_3stage_test",
    # "readtimes_currentread_test",
    # "readtimes_inferread_test",
    # "readtimes_voltageread_test",
    # "instr_infer_calibration2_test",
    # "instr_infer_calibration3_test",
    # "instr_calibration_infermode_test",
    # "instr_inference_infermode_test",
    # "instr_inference_infermode1_test",
    # "instr_inference_infermode2_test",
    # "instr_inference_infermode_norm_switch_test",
    # "infer_10logicid_test",
    # "currentread_10logicid_test",
    # "inferread_10logicid_test",
    # "voltageread_10logicid_test",
    # "instr_program_3stage_merge_test",
    # "pvt_sensor_base_test",
    # "pvt_sensor_temp_test",
    # "pvt_sensor_temp_up_test",
    # "pvt_sensor_temp_dn_test",
    # "pvt_sensor_alarm_test",
    # "pvt_sensor_average_test",
    # "pvt_sensor_automatic_test",
    # "pvt_sensor_cfgburst_test",
    # "pvt_sensor_mask_test",
    # "pvt_sensor_volt_test",
    # "pvt_sensor_proc_test",
    # "pvt_sensor_temp_volt_test",
    # "pvt_sensor_temp_proc_test",
    # "pvt_sensor_volt_proc_test",
    # "pvt_sensor_async_temp_test",
    # "pvt_sensor_async_volt_test",
    # "pvt_sensor_async_proc_test",
    # "barrier_addctest_test",
    # "barrier_arraytimingctrl_test",
    # "barrier_calibration_test",
    # "barrier_config_test",
    # "barrier_currentread_test",
    # "barrier_dactest_test",
    # "barrier_erase_test",
    # "barrier_inference_test",
    # "barrier_inferread_test",
    # "barrier_program_test",
    # "barrier_voltageread_test",
    # "barrier_debugdac_cleardac_test",
    # "instr_writecompbuffer_part_test",
    # "inference_trace_test",
    # "calibration_trace_test",
    # "read_voltageread_852_142_test",
    # "read_voltageread_barrier_id_test",
    # "read_voltageread_base_test",
    # "read_voltageread_blselmode_test",
    # "read_voltageread_cellsum_test",
    # "read_voltageread_gen_sar_adc_addr_test",
    # "read_voltageread_id_test",
    # "read_voltageread_inner_sel_test",
    # "read_voltageread_intren_test",
    # "read_voltageread_osize_test",
    # "read_voltageread_packetsize_test",
    # "read_voltageread_pgagain_test",
    # "read_voltageread_ph_sel_test",
    # "read_voltageread_randround_test",
    # "read_voltageread_readtimes_test",
    # "read_currentread_barrier_id_test",
    # "read_currentread_base_test",
    # "read_currentread_bias_cellsum_test",
    # "read_currentread_bias_innercell_test",
    # "read_currentread_bias_nssel_test",
    # "read_currentread_bias_readtimes_test",
    # "read_currentread_bias_value_test",
    # "read_currentread_blselmode_test",
    # "read_currentread_id_test",
    # "read_currentread_intren_test",
    # "read_currentread_osize_test",
    # "read_currentread_packetsize_test",
    # "read_currentread_randround_test",
    # "read_currentread_weight_852_142_test",
    # "read_currentread_weight_cellsum_test",
    # "read_currentread_weight_dac_test",
    # "read_currentread_weight_pgagain_test",
    # "read_currentread_weight_randcell_test",
    # "read_currentread_weight_readtimes_test",
    # "read_inferread_base_test",
    # "read_inferread_bias_innercell_test",
    # "read_inferread_bias_nssel_test",
    # "read_inferread_bias_value_test",
    # "read_inferread_blselmode_test",
    # "read_inferread_id_test",
    # "read_inferread_intren_test",
    # "read_inferread_osize_test",
    # "read_inferread_packsize_test",
    # "read_inferread_paggain_test",
    # "read_inferread_randround_test",
    # "read_inferread_weight_852_142_test",
    # "read_inferread_weight_cellsum_test",
    # "read_inferread_weight_dac_test",
    # "read_inferread_weight_innercell_test",
    # "selfloop_infer_1table_test",
    # "selfloop_infer_1table_autostop_test",
    # "selfloop_infer_start_mode2_test",
    # "selfloop_infer_start_mode3_test",
    # "selfloop_infer_start_mode4_test",
    # "selfloop_infer_start_mode5_test",
    # "selfloop_infer_start_mode6_test",
    # "selfloop_infer_start_mode7_test",
    # "selfloop_infer_start_mode8_test",
    # "selfloop_infer_start_mode9_test",
    # "selfloop_addtime_test",
    # "instr_calibration_infermode1_test",
    # "instr_calibration_infermode2_test",
    # "instr_calibration_infermode_norm_switch_test",
    # "adc_debug_reg_test",
    # "tia_debug_reg_test",
    # "debug_dac_dn_reg_test",
    # "debug_dac_up_reg_test",
    # "debug_dac_dn_tsv_reg_reg_test",
    # "debug_dac_up_tsv_reg_reg_test",
    # "nop_adctest_test",
    # "nop_arraytimingctrl_test",
    # "nop_dactest_test",
    # "nop_debugdac_test",
    # "nop_readburst_test",
    # "instr_debugdac_apb_redunt_test",
    # "inference_calibration_trace_test",
    # "debug_dac_up_reg_reg_test",
    # "debug_dac_dn_tsv_reg_reg_test",
    # "debug_dac_up_tsv_reg_reg_test",
    # "nop_adctest_test",
    # "nop_arraytimingctrl_test",
    # "nop_dactest_test",
    # "nop_debugdac_test",
    # "nop_readburst_test",
    # "instr_debugdac_apb_redunt_test",
    # "inference_calibration_trace_test",
    # "dscarrayctrl_currentread_freeze_test",
    # "dscarrayctrl_inferread_freeze_test",
    # "dscarrayctrl_voltageread_freeze_test",
    # "dscarrayctrl_calibration_freeze_test",
    # "backpress_bypass_ipkt_test",
    # "backpress_bypass_opkt_test",
    # "backpress_currentread_opkt_test",
    # "backpress_inferread_opkt_test",
    # "backpress_voltageread_opkt_test",
    # "instr_inference_recfg_tia_test",        
#==========================================================    
    "backpress_bypass_ipkt",
    "backpress_adctest_opkt",
    "backpress_dactest_opkt",
    "backpress_bypass_opkt",
    "backpress_debugdac_apb_opkt",
    "backpress_currentread_opkt",
    "backpress_inference_ipkt",
    "backpress_inference_opkt",
    "backpress_inferread_opkt",
    "backpress_voltageread_opkt",
    "abnormal_calibration_payload",
    "abnormal_adctest_head",
    "abnormal_calibration_head",
    "abnormal_bypass_head",
    "abnormal_bypass_payload",
    "abnormal_adctest_payload",
    "abnormal_configburst_head",
    "abnormal_cleardac_payload",
    "abnormal_configsingle_head",
    "abnormal_arraytimingctrl_payload",
    "abnormal_configburst_payload",
    "abnormal_cleardac_head",
    "abnormal_debugdac_head",
    "abnormal_configimm_head",
    "abnormal_currentread_head",
    "abnormal_currentread_payload",
    "abnormal_configimm_payload",
    "abnormal_debugdac_payload",
    "abnormal_dactest_payload",
    "abnormal_erase_payload",
    "abnormal_configsingle_payload",
    "abnormal_delay_payload",
    "abnormal_inferread_head",
    "abnormal_inference_head",
    "abnormal_flash_die_error",
    "abnormal_fence_head",
    "abnormal_inference_payload",
    "abnormal_fence_payload",
    "abnormal_erase_head",
    "abnormal_readburst_head",
    "abnormal_inferread_payload",
    "abnormal_readburst_payload",
    "abnormal_program_head",
    "abnormal_opcode",
    "abnormal_reset_head",
    "abnormal_program_payload",
    "abnormal_dactest_head",
    "abnormal_delay_head",
    "abnormal_voltageread_payload",
    "abnormal_voltageread_head",
    "abnormal_reset_payload",
    "abnormal_writecompbuffer_head",
    "abnormal_writecompbuffer_payload",
    "abnormal_writetiabuffer_head",
    "abnormal_writetiabuffer_payload",
#miniregression=================================================================================
    "instr_readburst",
    "nop_configburst",
    "nop_bypass",
    "instr_configburst",
    "nop_configimm",
    "instr_configsingle",
    "instr_configimm",
    "nop_configsingle",
    "instr_bypass",
    "nop_debugdac",
    "instr_debugdac",
    "instr_readburst_table",
    "nop_readburst",
    "instr_configsingle_table",
    "instr_erase",
    "instr_program",
    "nop_program",
    "nop_erase",
    "instr_configburst_table",
    "nop_voltageread",
    "instr_writetiabuffer",
    "nop_writetiabuffer",
    "instr_adctest",
    "nop_writecompbuffer",
    "instr_writecompbuffer",
    "nop_adctest",
    "instr_voltageread",
    "nop_dactest",
    "nop_delay",
    "instr_delay",
    "instr_dactest",
    "nop_currentread",
    "nop_calibration",
    "nop_inferread",
    "instr_calibration",
    "instr_inference",
    "inference_single_tia",
    "nop_inference",
    "instr_currentread",
    "instr_inferread",
    "multi_selfloop_autostop"    
]
