instrlist = [
    # "instr_inference_test_test",
    # "instr_inference_performance_test_test",
    # "instr_calibration_test_test",
    # "instr_program_test_test",
    # "instr_program_process1_test_test",
    # "instr_voltageread_test_test",
    # "instr_currentread_test_test",
    # "instr_inferread_test_test",
    # "instr_erase_test_test",
    # "instr_configimm_test_test",
    # "instr_configsingle_test_test",
    # "instr_configsingle_table_test_test",
    # "instr_configburst_test_test",
    # "instr_configburst_table_test_test",
    # "instr_readburst_test_test",
    # "instr_readburst_table_test_test",
    # "instr_writetiabuffer_test_test",
    # "instr_writecompbuffer_test_test",
    # "instr_writebuffer_test_test",
    # "instr_bypass_test_test",
    # "instr_fence_test_test",
    # "instr_delay_test_test",
    # "instr_tia_test_test",
    # "instr_tia_part_test_test",
    # "instr_comp_test_test",
    # "instr_erase_program_calibration_test_test",
    # "instr_erase_program_currentread_test_test",
    # "instr_erase_program_currentread_1table_test_test",
    # "instr_erase_program_inferread_test_test",
    # "instr_erase_program_inferread_1table_test_test",
    # "instr_erase_program_inference_test_test",
    # "instr_erase_program_inference_1table_test_test",
    # "instr_erase_program_voltageread_test_test",
    # "instr_erase_program_voltageread_1table_test_test",
    # "instr_infer_bypass_test_test",
    # "instr_infer_calibration_test_test",
    # "instr_infer_currentread_test_test",
    # "instr_infer_erase_test_test",
    # "instr_infer_erase_1table_test_test",
    # "instr_infer_inferread_test_test",
    # "instr_infer_program_test_test",
    # "instr_infer_program_1table_test_test",
    # "instr_infer_voltageread_test_test",
    # "instr_layer_sel_test_test",
    # "reg_cfg_test_test",
    # "instr_config_fence_test_test",
    # "instr_currentread_fence_test_test",
    # "instr_erase_fence_test_test",
    # "instr_inferread_fence_test_test",
    # "instr_program_fence_test_test",
    # "instr_voltageread_fence_test_test",
    # "instr_config_delay_test_test",
    # "instr_erase_delay_test_test",
    # "instr_program_delay_test_test",
    # "instr_currentread_delay_test_test",
    # "instr_inferread_delay_test_test",
    # "instr_voltageread_delay_test_test",
    # "instr_calibration_erase_test_test",
    # "instr_calibration_program_test_test",
    # "instr_calibration_currentread_test_test",
    # "instr_calibration_inferread_test_test",
    # "instr_calibration_voltageread_test_test",
    # "instr_switch_test_test",
    # "instr_switch_1table_test_test",
    # "instr_switch_1table_list1_test_test",
    # "rcc_reg_test_test",
    # "reg_map_reg_test_test",
    # "common_reg_test_test",
    # "dacfifo5_reg_test_test",
    # "post_ctrl_reg_test_test",
    # "pipepre_reg_test_test",
    # "prim_register_reg_test_test",
    # "comp_sram_wr_rd_test_test",
    # "boundary_config_regaddr_test_test",
    # "tia_sram_wr_rd_test_test",
    # "logic_reg_perf_test_test",
    # "flash_reg_pref_test_test",
    # "regall_reg_test_test",
    # "tia_backdoor_test_test",
    # "pvt_reg_reg_test_test",
    # "comp_backdoor_test_test",
    # "regall_addr_scan_test_test",
    # "regall_outaddr_scan_test_test",
    # "buffer_multi_wr_rd_test_test",
    # "comp_same_addr_wr_rd_test_test",
    # "single_infer_pipemode1_test_test",
    # "single_infer_pipemode2_test_test",
    # "single_infer_pipemode3_test_test",
    # "single_infer_pipemode1_rand_test_test",
    # "single_infer_pipemode2_rand_test_test",
    # "single_infer_pipemode3_rand_test_test",
    # "multi_infer_pipemode1_test_test",
    # "multi_infer_pipemode2_test_test",
    # "multi_infer_pipemode3_test_test",
    # "multi_infer_pipemode1_rand_test_test",
    # "multi_infer_pipemode2_rand_test_test",
    # "multi_infer_pipemode3_rand_test_test",
    # "multi_infer_pipemode1_min_test_test",
    # "multi_infer_pipemode2_min_test_test",
    # "multi_infer_pipemode3_min_test_test",
    # "multi_infer_pipemode1_max_test_test",
    # "multi_infer_pipemode2_max_test_test",
    # "multi_infer_pipemode3_max_test_test",
    # "infer_row_remap_test_test",
    # "infer_col_remap_test_test",
    # "infer_pre_scale_test_test",
    # "infer_post_comp_test_test",
    # "infer_post_scale_test_test",
    # "infer_post_shift_test_test",
    # "infer_post_cascade_test_test",
    # "pre_currentread_test_test",
    # "pre_currentread_red_test_test",
    # "pre_inferread_test_test",
    # "pre_inferread_red_test_test",
    # "pre_dactest_test_test",
    # "post_read_test_test",
    # "post_adctest_test_test",
    # "post_dactest_test_test",
    # "post_readburst_test_test",
    # "boundary_bypass_test_test",
    # "boundary_config_regaddr_test_test",
    # "boundary_calibration_test_test",
    # "boundary_config_test_test",
    # "boundary_currentread_test_test",
    # "boundary_delay_test_test",
    # "boundary_erase_test_test",
    # "boundary_inference_test_test",
    # "boundary_inferread_test_test",
    # "boundary_program_test_test",
    # "boundary_voltageread_test_test",
    # "boundary_writebuffer_test_test",
    # "instr_infer_redundant_row_test_test",
    # "instr_infer_redundant_bias_test_test",
    # "instr_infer_redundant_col_test_test",
    # "instr_redundant_currentread_test_test",
    # "instr_redundant_erase_test_test",
    # "instr_redundant_inferread_test_test",
    # "instr_redundant_program_test_test",
    # "instr_redundant_voltageread_test_test",
    # "instr_redundant_inference_test_test",
    # "blsel_currentread_test_test",
    # "blsel_inferread_test_test",
    # "blsel_instr_switch_test_test",
    # "blsel_program_test_test",
    # "blsel_voltageread_test_test",
    # "instr_debugdac_test_test",
    # "instr_debugdac_apb_test_test",
    # "inster_addctest_test_test",
    # "inster_dactest_test_test",
    # "instr_dactest_customize_length_test_test",
    # "instr_dactest_customize_length_pad_test_test",
    # "instr_dactest_customize_length_bypasstia_test_test",
    # "nop_calibration_test_test",
    # "nop_config_test_test",
    # "nop_currentread_test_test",
    # "nop_delay_test_test",
    # "nop_erase_test_test",
    # "nop_fence_test_test",
    # "nop_inference_test_test",
    # "nop_inferread_test_test",
    # "nop_program_test_test",
    # "nop_voltageread_test_test",
    # "nop_writecompbuffer_test_test",
    # "nop_writetiabuffer_test_test",
    # "reuse_inference_test_test",
    # "reuse_inference_calibration_test_test",
    # "reuse_calibration_test_test",
    # "backpress_infer_opkt_first_test_test",
    # "backpress_infer_opkt_mid_test_test",
    # "backpress_infer_opkt_test_test",
    # "backpress_calib_opkt_test_test",
    # "backpress_infer_calib_opkt_test_test",
    # "backpress_infer_ipkt_test_test",
    # "cellsum_calibration_test_test",
    # "cellsum_currentread_test_test",
    # "cellsum_inference_test_test",
    # "cellsum_inferread_test_test",
    # "cellsum_voltagread_test_test",
    # "dscarrayctrl_infer_freeze_test_test",
    # "reset_in_idle_test_test",
    # "reset_barrier_id_test_test",
    # "instr_currentread_3stage_test_test",
    # "instr_inference_3stage_test_test",
    # "instr_inferread_3stage_test_test",
    # "instr_program_3stage_cg_test_test",
    # "instr_program_3stage_s1_test_test",
    # "instr_voltageread_3stage_test_test",
    # "readtimes_currentread_test_test",
    # "readtimes_inferread_test_test",
    # "readtimes_voltageread_test_test",
    # "instr_infer_calibration2_test_test",
    # "instr_infer_calibration3_test_test",
    # "instr_calibration_infermode_test_test",
    # "instr_inference_infermode_test_test",
    # "instr_inference_infermode1_test_test",
    # "instr_inference_infermode2_test_test",
    # "instr_inference_infermode_norm_switch_test_test",
    # "infer_10logicid_test_test",
    # "currentread_10logicid_test_test",
    # "inferread_10logicid_test_test",
    # "voltageread_10logicid_test_test",
    # "instr_program_3stage_merge_test_test",
    # "pvt_sensor_base_test_test",
    # "pvt_sensor_temp_test_test",
    # "pvt_sensor_temp_up_test_test",
    # "pvt_sensor_temp_dn_test_test",
    # "pvt_sensor_alarm_test_test",
    # "pvt_sensor_average_test_test",
    # "pvt_sensor_automatic_test_test",
    # "pvt_sensor_cfgburst_test_test",
    # "pvt_sensor_mask_test_test",
    # "pvt_sensor_volt_test_test",
    # "pvt_sensor_proc_test_test",
    # "pvt_sensor_temp_volt_test_test",
    # "pvt_sensor_temp_proc_test_test",
    # "pvt_sensor_volt_proc_test_test",
    # "pvt_sensor_async_temp_test_test",
    # "pvt_sensor_async_volt_test_test",
    # "pvt_sensor_async_proc_test_test",
    # "barrier_addctest_test_test",
    # "barrier_arraytimingctrl_test_test",
    # "barrier_calibration_test_test",
    # "barrier_config_test_test",
    # "barrier_currentread_test_test",
    # "barrier_dactest_test_test",
    # "barrier_erase_test_test",
    # "barrier_inference_test_test",
    # "barrier_inferread_test_test",
    # "barrier_program_test_test",
    # "barrier_voltageread_test_test",
    # "barrier_debugdac_cleardac_test_test",
    # "instr_writecompbuffer_part_test_test",
    # "inference_trace_test_test",
    # "calibration_trace_test_test",
    # "read_voltageread_852_142_test_test",
    # "read_voltageread_barrier_id_test_test",
    # "read_voltageread_base_test_test",
    # "read_voltageread_blselmode_test_test",
    # "read_voltageread_cellsum_test_test",
    # "read_voltageread_gen_sar_adc_addr_test_test",
    # "read_voltageread_id_test_test",
    # "read_voltageread_inner_sel_test_test",
    # "read_voltageread_intren_test_test",
    # "read_voltageread_osize_test_test",
    # "read_voltageread_packetsize_test_test",
    # "read_voltageread_pgagain_test_test",
    # "read_voltageread_ph_sel_test_test",
    # "read_voltageread_randround_test_test",
    # "read_voltageread_readtimes_test_test",
    # "read_currentread_barrier_id_test_test",
    # "read_currentread_base_test_test",
    # "read_currentread_bias_cellsum_test_test",
    # "read_currentread_bias_innercell_test_test",
    # "read_currentread_bias_nssel_test_test",
    # "read_currentread_bias_readtimes_test_test",
    # "read_currentread_bias_value_test_test",
    # "read_currentread_blselmode_test_test",
    # "read_currentread_id_test_test",
    # "read_currentread_intren_test_test",
    # "read_currentread_osize_test_test",
    # "read_currentread_packetsize_test_test",
    # "read_currentread_randround_test_test",
    # "read_currentread_weight_852_142_test_test",
    # "read_currentread_weight_cellsum_test_test",
    # "read_currentread_weight_dac_test_test",
    # "read_currentread_weight_pgagain_test_test",
    # "read_currentread_weight_randcell_test_test",
    # "read_currentread_weight_readtimes_test_test",
    # "read_inferread_base_test_test",
    # "read_inferread_bias_innercell_test_test",
    # "read_inferread_bias_nssel_test_test",
    # "read_inferread_bias_value_test_test",
    # "read_inferread_blselmode_test_test",
    # "read_inferread_id_test_test",
    # "read_inferread_intren_test_test",
    # "read_inferread_osize_test_test",
    # "read_inferread_packsize_test_test",
    # "read_inferread_paggain_test_test",
    # "read_inferread_randround_test_test",
    # "read_inferread_weight_852_142_test_test",
    # "read_inferread_weight_cellsum_test_test",
    # "read_inferread_weight_dac_test_test",
    # "read_inferread_weight_innercell_test_test",
    # "selfloop_infer_1table_test_test",
    # "selfloop_infer_1table_autostop_test_test",
    # "selfloop_infer_start_mode2_test_test",
    # "selfloop_infer_start_mode3_test_test",
    # "selfloop_infer_start_mode4_test_test",
    # "selfloop_infer_start_mode5_test_test",
    # "selfloop_infer_start_mode6_test_test",
    # "selfloop_infer_start_mode7_test_test",
    # "selfloop_infer_start_mode8_test_test",
    # "selfloop_infer_start_mode9_test_test",
    # "selfloop_addtime_test_test",
    # "instr_calibration_infermode1_test_test",
    # "instr_calibration_infermode2_test_test",
    # "instr_calibration_infermode_norm_switch_test_test",
    # "adc_debug_reg_test_test",
    # "tia_debug_reg_test_test",
    # "debug_dac_dn_reg_test_test",
    # "debug_dac_up_reg_test_test",
    # "debug_dac_dn_tsv_reg_reg_test_test",
    # "debug_dac_up_tsv_reg_reg_test_test",
    # "nop_adctest_test_test",
    # "nop_arraytimingctrl_test_test",
    # "nop_dactest_test_test",
    # "nop_debugdac_test_test",
    # "nop_readburst_test_test",
    # "instr_debugdac_apb_redunt_test_test",
    # "inference_calibration_trace_test_test",
    # "debug_dac_up_reg_reg_test_test",
    # "debug_dac_dn_tsv_reg_reg_test_test",
    # "debug_dac_up_tsv_reg_reg_test_test",
    # "nop_adctest_test_test",
    # "nop_arraytimingctrl_test_test",
    # "nop_dactest_test_test",
    # "nop_debugdac_test_test",
    # "nop_readburst_test_test",
    # "instr_debugdac_apb_redunt_test_test",
    # "inference_calibration_trace_test_test",
    # "dscarrayctrl_currentread_freeze_test_test",
    # "dscarrayctrl_inferread_freeze_test_test",
    # "dscarrayctrl_voltageread_freeze_test_test",
    # "dscarrayctrl_calibration_freeze_test_test",
    # "backpress_bypass_ipkt_test_test",
    # "backpress_bypass_opkt_test_test",
    # "backpress_currentread_opkt_test_test",
    # "backpress_inferread_opkt_test_test",
    # "backpress_voltageread_opkt_test_test",
    # "instr_inference_recfg_tia_test_test",        
#==========================================================    
    "backpress_bypass_ipkt_test",
    "backpress_adctest_opkt_test",
    "backpress_dactest_opkt_test",
    "backpress_bypass_opkt_test",
    "backpress_debugdac_apb_opkt_test",
    "backpress_currentread_opkt_test",
    "backpress_inference_ipkt_test",
    "backpress_inference_opkt_test",
    "backpress_inferread_opkt_test",
    "backpress_voltageread_opkt_test",
    "abnormal_calibration_payload_test",
    "abnormal_adctest_head_test",
    "abnormal_calibration_head_test",
    "abnormal_bypass_head_test",
    "abnormal_bypass_payload_test",
    "abnormal_adctest_payload_test",
    "abnormal_configburst_head_test",
    "abnormal_cleardac_payload_test",
    "abnormal_configsingle_head_test",
    "abnormal_arraytimingctrl_payload_test",
    "abnormal_configburst_payload_test",
    "abnormal_cleardac_head_test",
    "abnormal_debugdac_head_test",
    "abnormal_configimm_head_test",
    "abnormal_currentread_head_test",
    "abnormal_currentread_payload_test",
    "abnormal_configimm_payload_test",
    "abnormal_debugdac_payload_test",
    "abnormal_dactest_payload_test",
    "abnormal_erase_payload_test",
    "abnormal_configsingle_payload_test",
    "abnormal_delay_payload_test",
    "abnormal_inferread_head_test",
    "abnormal_inference_head_test",
    "abnormal_flash_die_error_test",
    "abnormal_fence_head_test",
    "abnormal_inference_payload_test",
    "abnormal_fence_payload_test",
    "abnormal_erase_head_test",
    "abnormal_readburst_head_test",
    "abnormal_inferread_payload_test",
    "abnormal_readburst_payload_test",
    "abnormal_program_head_test",
    "abnormal_opcode_test",
    "abnormal_reset_head_test",
    "abnormal_program_payload_test",
    "abnormal_dactest_head_test",
    "abnormal_delay_head_test",
    "abnormal_voltageread_payload_test",
    "abnormal_voltageread_head_test",
    "abnormal_reset_payload_test",
    "abnormal_writecompbuffer_head_test",
    "abnormal_writecompbuffer_payload_test",
    "abnormal_writetiabuffer_head_test",
    "abnormal_writetiabuffer_payload_test",
#miniregression=================================================================================
    "instr_readburst_test",
    "nop_configburst_test",
    "nop_bypass_test",
    "instr_configburst_test",
    "nop_configimm_test",
    "instr_configsingle_test",
    "instr_configimm_test",
    "nop_configsingle_test",
    "instr_bypass_test",
    "nop_debugdac_test",
    "instr_debugdac_test",
    "instr_readburst_table_test",
    "nop_readburst_test",
    "instr_configsingle_table_test",
    "instr_erase_test",
    "instr_program_test",
    "nop_program_test",
    "nop_erase_test",
    "instr_configburst_table_test",
    "nop_voltageread_test",
    "instr_writetiabuffer_test",
    "nop_writetiabuffer_test",
    "instr_adctest_test",
    "nop_writecompbuffer_test",
    "instr_writecompbuffer_test",
    "nop_adctest_test",
    "instr_voltageread_test",
    "nop_dactest_test",
    "nop_delay_test",
    "instr_delay_test",
    "instr_dactest_test",
    "nop_currentread_test",
    "nop_calibration_test",
    "nop_inferread_test",
    "instr_calibration_test",
    "instr_inference_test",
    "inference_single_tia_test",
    "nop_inference_test",
    "instr_currentread_test",
    "instr_inferread_test",
    "multi_selfloop_autostop_test",    
    "abnormal_pll_lock_test",
    "abnormal_register_access_test",
    "abnormal_buf_access_test",
    "abnormal_timeout_fd_dacff28_in_test",
    #============================    

"inference_barrier_test",
"inference_boundary_test",
"inference_cellsum_test",
"inference_bigdata_test",
"inference_dscarrayctrl_freeze_test",
"inference_bigdata_dyn_logicid_test",
"inference_dyn_logicid_test",
"inference_dyn_recfg_tia_test",
"inference_infermode1_test",
"inference_infermode2_test",
"inference_infermode_norm_switch_test",
"inference_infermode_test",
"inference_performance_bigdata_test",
"inference_performance_test",
"inference_recfg_tia_test",
"inference_reuse_test",
"inference_trace_test",
"inference_calibration_trace_test",
"erase_barrier_test",
"erase_boundary_test",
"erase_dscarrayctrl_freeze_test",
"program_barrier_test",
"program_blsel_test",
"program_boundary_test",
"program_dscarrayctrl_freeze_test",
"program_merge_timing_test",
"program_repeat_test",
"voltageread_barrier_test",
"voltageread_blsel_test",
"voltageread_boundary_test",
"voltageread_cellsum_test",
"voltageread_dscarrayctrl_freeze_test",
"voltageread_readtimes_test",
"voltageread_dyn_readtimes_test",
"currentread_barrier_test",
"currentread_blsel_test",
"currentread_boundary_test",
"currentread_cellsum_test",
"currentread_dscarrayctrl_freeze_test",
"currentread_readtimes_test",
"currentread_dyn_readtimes_test",
"inferread_barrier_test",
"inferread_blsel_test",
"inferread_boundary_test",

"inferread_dscarrayctrl_freeze_test",
"inferread_readtimes_test",
"inferread_dyn_readtimes_test",
"arraytimingctrl_dscarrayctrl_freeze_test",
"config_barrier_test",
"config_boundary_test",
"bypass_boundary_test",
"dactest_barrier_test",
"dactest_customize_length_bypasstia_test",
"dactest_customize_length_pad_test",
"dactest_customize_length_test",
"dactest_dscarrayctrl_freeze_test",
"debugdac_apb_test",
"debugdac_barrier_test",
"adctest_barrier_test",
"adctest_dscarrayctrl_freeze_test",
"delay_boundary_test",
"selfloop_addtime_test",
"selfloop_infer_start_mode1_test",
"selfloop_infer_start_mode2_test",
"selfloop_infer_start_mode3_test",
"selfloop_infer_start_mode4_test",
"selfloop_infer_start_mode5_test",
"selfloop_infer_start_mode6_test",
"selfloop_infer_start_mode7_test",
"selfloop_infer_start_mode8_test",
"selfloop_infer_start_mode9_test",
"redundant_bias_infer_test",
"redundant_boundary_row_infer_test",
"redundant_col_infer_test",
"redundant_currentread_test",
"redundant_erase_test",
"redundant_inferread_test",
"redundant_program_test",
"redundant_debugdac_apb_test",


"redundant_voltageread_test",
"combine_erase_program_adctest_1table_test",


"combine_erase_program_adctest_test",

"combine_erase_program_debugdac_1table_test",
"combine_erase_program_debugdac_test",

"combine_blsel_in_read_test",
"combine_erase_program_inference_test",
"combine_erase_program_dactest_1table_test",
"combine_erase_program_voltageread_1table_test",
"combine_erase_program_voltageread_test",
"combine_erase_program_dactest_test",




"buf_outstanding_tia_test",
"buf_outstanding_comp_test",



"buf_read_blsel_voltageread_test",
"redundant_row_infer_test",
"combine_erase_program_inference_1table_test",
"buf_read_outstanding_comp_test",
"buf_read_progdone_test",

"buf_read_outstanding_tia_test",

"inferread_cellsum_test",
"combine_instr_switch_1table_test",





"combine_inference_calibration_test",

"buf_read_blsel_inferread_test",
"combine_inference_bypass_test",


"combine_erase_program_currentread_test",
"buf_read_blsel_currentread_test",
"combine_instr_switch_test",


"abnormal_inference_poison_test",
"instr_reset_all_test",
"combine_erase_program_currentread_1table_test",
"combine_erase_program_inferread_1table_test",
"combine_erase_program_inferread_test",
"currentread_tia_test",
"selfloop_fc_auto_start_test",
"selfloop_fc_fd_auto_start_test",
"selfloop_fd_auto_start_test",
"inference_infermode2_same_timing_test",
"inference_infermode0_same_timing_test",
"selfloop_fc_duty_test",
"abnormal_timeout_fc_download_dacff5_in_test",
"abnormal_timeout_fc_download_dacff5_out_test",
"abnormal_timeout_fc_download_issue_test",
"abnormal_timeout_fd_download_tia_read_test",
"abnormal_timeout_fd_download_dacff28_in_test",
"abnormal_timeout_fc_download_parser_test",
"abnormal_timeout_fd_download_dacff28_out_test",
"abnormal_timeout_fd_download_dacff28_inner_test",
"abnormal_timeout_fd_upload_adc_test_ready_test",
"abnormal_timeout_apb_test",
"abnormal_fc_set_error_test",
"abnormal_timeout_fc_upload_post_proc_test",
"abnormal_timeout_fd_upload_adc_ready_test",
"abnormal_fc_set_debug_ipkt_param_error_test",
"abnormal_fc_set_cim_ipkt_param_error_test",
"abnormal_fc_set_ram_error_test",
"abnormal_fc_set_timeout_error_test",
"abnormal_fc_set_cfg_ipkt_param_error_test",
"abnormal_fc_set_fifo_error_test",
"combine_erase_program_voltageread_1table_2_test",
"selfloop_fd_duty_test",
"selfloop_fc_fd_duty_test",
"combine_erase_program_inference_1table_2_test",
"combine_erase_program_currentread_1table_2_test"
]
