#!/bin/bash
# Generated by run_cmd_creater.py
# Date: 20260320
# Total tests: 4

# Test 1: testlist/tc_basic_read
source /etc/profile && bsub -q to2 run -l testlist/tc_basic_read 	 -sim "+wave_dump=on -cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260320/tc_basic_read -g  -p 10  -seed_offset 20260320 -sim "+UVM_VERBOSITY=UVM_NONE" -b "bsub -q to2 timeout 2400m "&

# Test 2: testlist/tc_basic_write
source /etc/profile && bsub -q to2 run -l testlist/tc_basic_write 	 -sim "+wave_dump=on -cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260320/tc_basic_write -g  -p 10  -seed_offset 20260320  -b "bsub -q to2 timeout 2400m "&

# Test 3: testlist/tc_burst_transfer
bsub -q to2 run -l testlist/tc_burst_transfer 	 -sim "+wave_dump=on -cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260320/tc_burst_transfer -g  -p 10  -seed_offset 20260320  -b "bsub -q to2 timeout 2400m "&

# Test 4: testlist/tc_error_handling
cd /path/to/error_test && source env.csh && export DEBUG=1 && bsub -q to2 run -l testlist/tc_error_handling 	 -sim "+wave_dump=on -cm line+cond+fsm+tgl+branch+assert " -simdir regression/regression_20260320/tc_error_handling -g  -p 10  -seed_offset 20260320  -b "bsub -q to2 timeout 2400m "&

